# Generated by Django 2.1.5 on 2019-02-03 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190203_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userblog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userblog', to=settings.AUTH_USER_MODEL),
        ),
    ]
