# Generated by Django 2.1.5 on 2019-03-06 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_auto_20190203_1743'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=250)),
                ('likes', models.IntegerField()),
                ('followers', models.IntegerField()),
                ('date', models.DateField()),
                ('male_users', models.IntegerField()),
                ('female_users', models.IntegerField()),
                ('totalPosts', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TumblrReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=250)),
                ('likes', models.IntegerField()),
                ('followers', models.IntegerField()),
                ('date', models.DateField()),
                ('male_users', models.IntegerField()),
                ('female_users', models.IntegerField()),
                ('totalPosts', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TwitterReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=250)),
                ('likes', models.IntegerField()),
                ('followers', models.IntegerField()),
                ('date', models.DateField()),
                ('male_users', models.IntegerField()),
                ('female_users', models.IntegerField()),
                ('totalPosts', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WordpressReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_name', models.CharField(max_length=250)),
                ('date', models.DateField()),
                ('totalPosts', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='userblog',
            name='password',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='userblog',
            name='username',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
