# Generated by Django 2.1.5 on 2019-03-24 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190306_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facebookreport',
            name='date',
        ),
        migrations.RemoveField(
            model_name='tumblrreport',
            name='date',
        ),
        migrations.RemoveField(
            model_name='twitterreport',
            name='date',
        ),
        migrations.RemoveField(
            model_name='wordpressreport',
            name='date',
        ),
        migrations.AddField(
            model_name='wordpressreport',
            name='avgPostLength',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wordpressreport',
            name='keywords',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='wordpressreport',
            name='sentiment_comments',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='wordpressreport',
            name='sentiment_posts',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='facebookreport',
            name='female_users',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='facebookreport',
            name='followers',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='facebookreport',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='facebookreport',
            name='male_users',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='facebookreport',
            name='totalPosts',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tumblrreport',
            name='female_users',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tumblrreport',
            name='followers',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tumblrreport',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tumblrreport',
            name='male_users',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tumblrreport',
            name='totalPosts',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='twitterreport',
            name='female_users',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='twitterreport',
            name='followers',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='twitterreport',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='twitterreport',
            name='male_users',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='twitterreport',
            name='totalPosts',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wordpressreport',
            name='totalPosts',
            field=models.IntegerField(default=0),
        ),
    ]
