# Generated by Django 2.1.5 on 2019-03-29 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190324_1318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facebookreport',
            old_name='female_users',
            new_name='femaleUsers',
        ),
        migrations.RenameField(
            model_name='facebookreport',
            old_name='male_users',
            new_name='maleUsers',
        ),
        migrations.RenameField(
            model_name='facebookreport',
            old_name='page_name',
            new_name='pageName',
        ),
        migrations.RenameField(
            model_name='tumblrreport',
            old_name='female_users',
            new_name='femaleUsers',
        ),
        migrations.RenameField(
            model_name='tumblrreport',
            old_name='male_users',
            new_name='maleUsers',
        ),
        migrations.RenameField(
            model_name='tumblrreport',
            old_name='page_name',
            new_name='pageName',
        ),
        migrations.RenameField(
            model_name='twitterreport',
            old_name='female_users',
            new_name='femaleUsers',
        ),
        migrations.RenameField(
            model_name='twitterreport',
            old_name='likes',
            new_name='following',
        ),
        migrations.RenameField(
            model_name='twitterreport',
            old_name='male_users',
            new_name='maleUsers',
        ),
        migrations.RenameField(
            model_name='twitterreport',
            old_name='page_name',
            new_name='pageName',
        ),
        migrations.RenameField(
            model_name='twitterreport',
            old_name='totalPosts',
            new_name='totalTweets',
        ),
        migrations.RenameField(
            model_name='wordpressreport',
            old_name='blog_name',
            new_name='blogName',
        ),
        migrations.RemoveField(
            model_name='wordpressreport',
            name='sentiment_comments',
        ),
        migrations.RemoveField(
            model_name='wordpressreport',
            name='sentiment_posts',
        ),
        migrations.AddField(
            model_name='twitterreport',
            name='loaction',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='twitterreport',
            name='sentimentReplies',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='twitterreport',
            name='sentimentTweets',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='wordpressreport',
            name='newComments',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wordpressreport',
            name='newPosts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wordpressreport',
            name='sentimentComments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='wordpressreport',
            name='sentimentPosts',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='wordpressreport',
            name='totalAuthors',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wordpressreport',
            name='totalComments',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wordpressreport',
            name='keywords',
            field=models.TextField(blank=True, max_length=400),
        ),
    ]
